//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inquiry
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Company { get; set; }
        public string Employee { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
